version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: rigpulse-monitor_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/loud-roar/rigpulse:0.5.7
    init: true
    restart: unless-stopped
    environment:
      RIGPULSE_DATA_DIR: /data
      RIGPULSE_POLL_SECONDS: "10"
    volumes:
      - ${APP_DATA_DIR}/data:/data
